-- liquibase formatted sql

-- changeset liquibase:1634099754-1
CREATE TABLE "public"."users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "google_id" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "first_name" TEXT NOT NULL,
  "last_name" TEXT NOT NULL,
  "created_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  "updated_at" TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);
-- changeset liquibase:1634099754-2
CREATE TABLE "public"."sessions" (
  "sid" VARCHAR NOT NULL,
  "sess" JSON NOT NULL,
  "expire" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT "session_pkey" PRIMARY KEY ("sid")
);
-- changeset liquibase:1634099754-3
ALTER TABLE
  "public"."users"
ADD
  CONSTRAINT "users_email_key" UNIQUE ("email");
-- changeset liquibase:1634099754-4
ALTER TABLE
  "public"."users"
ADD
  CONSTRAINT "users_google_id_key" UNIQUE ("google_id");
-- changeset liquibase:1634099754-5
CREATE INDEX "IDX_session_expire" ON "public"."sessions"("expire");

-- changeset alex:1634100310
ALTER TABLE public.users
  ADD COLUMN access_token text NOT NULL,
  ADD COLUMN refresh_token text NOT NULL;
