name: Cypress

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.4
        env:
          POSTGRES_DB: caltsar_test
          POSTGRES_PASSWORD: password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      # set up the db
      - run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client
          sudo apt-get install --yes tree
      - run: psql -h localhost -d caltsar_test -U postgres -c 'SELECT 1;'
        env:
          PGPASSWORD: password
      - run: psql -h localhost -d caltsar_test -U postgres -f ./server/sql/changelog/changelog.postgresql.sql
        env:
          PGPASSWORD: password
      - run: psql -h localhost -d caltsar_test -U postgres -f ./server/sql/seed.sql
        env:
          PGPASSWORD: password

      # do npm / node stuff now
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: |
            client/package-lock.json
            server/package-lock.json
      - run: npm install
        working-directory: server
      - run: npm run build
        working-directory: server
      - run: node dist/server.js &
        working-directory: server
        env:
          PORT: 3000
          CLIENT_ID: "486498242972-v25cm8ku0pbdbi4c1fraoqoaqvegs94j.apps.googleusercontent.com"
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          NODE_ENV: development
          PGUSER: postgres
          PGHOST: localhost
          PGPASSWORD: password
          PGDATABASE: caltsar_test
          PGPORT: 5432
          COOKIE_SECRET: bad kitty
          FRONTEND_URI: http://localhost:3001
          TEST_USER_ID: 1
      - run: npm install
        working-directory: client
      - run: npm run build --if-present
        working-directory: client
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          REACT_APP_WEB_PORT: 3001
          REACT_APP_API_PORT: 3000
          REACT_APP_API_HOSTNAME: localhost
          REACT_APP_API_PROTOCOL: http
          PORT: 3001
        with:
          start: npm start
          browser: firefox
          wait-on: 'http://localhost:3001'
          wait-on-timeout: 120
          record: false
          parallel: false
          working-directory: client
          command: npm run cypress:run
